holds(at(elevator(1),7),0).
holds(request(deliver(1),9),0).
holds(request(call(up),3),0).
holds(request(call(up),1),0).
holds(request(call(down),6),0).
holds(request(call(down),9),0).
holds(request(call(down),7),0).
holds(at(elevator(1),7),1).
holds(request(call(down),9),1).
holds(request(call(down),6),1).
holds(request(call(up),1),1).
holds(request(call(up),3),1).
holds(request(deliver(1),9),1).
do(elevator(1),serve,1).
holds(at(elevator(1),8),2).
do(elevator(1),move(1),2).
holds(request(call(up),3),2).
holds(request(call(up),1),2).
holds(request(call(down),6),2).
holds(request(call(down),9),2).
holds(request(deliver(1),9),2).
holds(at(elevator(1),9),3).
do(elevator(1),move(1),3).
holds(request(deliver(1),9),3).
holds(request(call(down),9),3).
holds(request(call(down),6),3).
holds(request(call(up),1),3).
holds(request(call(up),3),3).
holds(at(elevator(1),9),4).
holds(request(call(up),3),4).
holds(request(call(up),1),4).
holds(request(call(down),6),4).
do(elevator(1),serve,4).
holds(at(elevator(1),8),5).
do(elevator(1),move(-1),5).
holds(request(call(down),6),5).
holds(request(call(up),1),5).
holds(request(call(up),3),5).
holds(at(elevator(1),7),6).
do(elevator(1),move(-1),6).
holds(request(call(up),3),6).
holds(request(call(up),1),6).
holds(request(call(down),6),6).
holds(at(elevator(1),6),7).
do(elevator(1),move(-1),7).
holds(request(call(down),6),7).
holds(request(call(up),1),7).
holds(request(call(up),3),7).
holds(at(elevator(1),6),8).
holds(request(call(up),3),8).
holds(request(call(up),1),8).
do(elevator(1),serve,8).
holds(at(elevator(1),5),9).
do(elevator(1),move(-1),9).
holds(request(call(up),1),9).
holds(request(call(up),3),9).
holds(at(elevator(1),4),10).
do(elevator(1),move(-1),10).
holds(request(call(up),3),10).
holds(request(call(up),1),10).
holds(at(elevator(1),3),11).
do(elevator(1),move(-1),11).
holds(request(call(up),1),11).
holds(request(call(up),3),11).
holds(at(elevator(1),3),12).
holds(request(call(up),1),12).
do(elevator(1),serve,12).
holds(at(elevator(1),2),13).
do(elevator(1),move(-1),13).
holds(request(call(up),1),13).
holds(at(elevator(1),1),14).
do(elevator(1),move(-1),14).
holds(request(call(up),1),14).
holds(at(elevator(1),1),15).
do(elevator(1),serve,15).
