holds(at(elevator(1),2),0).
holds(request(deliver(1),3),0).
holds(request(call(up),1),0).
holds(at(elevator(1),3),1).
do(elevator(1),move(1),1).
holds(request(call(up),1),1).
holds(request(deliver(1),3),1).
holds(at(elevator(1),3),2).
holds(request(call(up),1),2).
do(elevator(1),serve,2).
holds(at(elevator(1),2),3).
do(elevator(1),move(-1),3).
holds(request(call(up),1),3).
holds(at(elevator(1),1),4).
do(elevator(1),move(-1),4).
holds(request(call(up),1),4).
holds(at(elevator(1),1),5).
do(elevator(1),serve,5).
