holds(at(elevator(1),4),0).
holds(request(deliver(1),5),0).
holds(request(call(up),2),0).
holds(at(elevator(1),5),1).
do(elevator(1),move(1),1).
holds(request(call(up),2),1).
holds(request(deliver(1),5),1).
holds(at(elevator(1),5),2).
holds(request(call(up),2),2).
do(elevator(1),serve,2).
holds(at(elevator(1),4),3).
do(elevator(1),move(-1),3).
holds(request(call(up),2),3).
holds(at(elevator(1),3),4).
do(elevator(1),move(-1),4).
holds(request(call(up),2),4).
holds(at(elevator(1),2),5).
do(elevator(1),move(-1),5).
holds(request(call(up),2),5).
holds(at(elevator(1),2),6).
do(elevator(1),serve,6).
