holds(at(elevator(1),1),0).
holds(at(elevator(2),2),0).
holds(request(deliver(2),3),0).
holds(request(call(up),3),0).
holds(request(call(down),5),0).
holds(request(call(down),4),0).
holds(at(elevator(2),3),1).
do(elevator(2),move(1),1).
holds(request(call(down),4),1).
holds(request(call(down),5),1).
holds(request(call(up),3),1).
holds(request(deliver(2),3),1).
holds(at(elevator(2),3),2).
holds(request(call(down),5),2).
holds(request(call(down),4),2).
do(elevator(2),serve,2).
holds(request(call(down),4),3).
holds(request(call(down),5),3).
holds(request(call(down),5),4).
holds(at(elevator(1),2),1).
do(elevator(1),move(1),1).
holds(at(elevator(1),3),2).
do(elevator(1),move(1),2).
holds(at(elevator(2),4),3).
holds(at(elevator(1),4),3).
do(elevator(1),move(1),3).
do(elevator(2),move(1),3).
holds(at(elevator(1),5),4).
holds(at(elevator(2),4),4).
do(elevator(2),serve,4).
do(elevator(1),move(1),4).
holds(at(elevator(2),4),5).
holds(at(elevator(1),5),5).
do(elevator(1),serve,5).
